version: "3.9"

services:
  app:
    build: .
    container_name: spring_boot_app
    depends_on:
      - db
    ports:
      - 8081:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fleetflow_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: fleetflow_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: